language: node_js
cache:
  directories:
  - "$HOME/build/unfoldingWord-dev/ts-desktop/node_modules"
sudo: false
node_js:
- '5.1'
before_script:
- npm install
- npm install gulp -g
script: gulp
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_54b2df9dba46_key -iv $encrypted_54b2df9dba46_iv
  -in config.json.enc -out unit_tests/git/config.json -d'
