language: node_js
node_js:
- '8'
os:
- linux
sudo: true
branches:
  except:
    - master
env:
  global:
  - secure: R61XmjAE1j2w1ynoBud6mliJX5Y73u9ncyVaSM9LajclYAEWRWD7n/bvAf8rfI/Al1FeLIedscMsfgdpBc4Lu+USO4NnH2cpjrWXQmU5xTF3sHSKK9a+jzHxa7kZQf+e2uePO39Ty7FypxBJ01Zsuiv6/Hv3PVpufZU60sywg/E=
  - secure: hiF+Sfpzc4C2Kxg+VgOHQ6ITPJRRwQJ802b6wnZy7Z1Ta9Gl01AgOFGWkf2raq4cQMlWw82UfiL7dEJ/bHwsEo3PoBMVhRG1AjiTY3dpoiKUjlX3MAl4SCZtBjmBN+4QT8HGOruhlKBG3xLNryg1UhjSbThPnw1rI//Be3IWH+o=
  - secure: TVM/SM0AXEVRKDFoLWhJy3zaCnlcOTxasWuufnnWPS1yyROPMUzel40OlByc4RJs0s7L7EPyFloBjF0hAwFB+KnPFsyrnLqvLto3egWEcfnA1rIjN98bM4y2qIF1TIuV7/DFIk5YJFhlDC8amc6l82yKtkdDb2LD4k0TKx3fySc=
#cache:
#  directories:
#  - node_modules
before_install:
- ./scripts/skip_travis_commits.sh
- sudo add-apt-repository --yes ppa:ubuntu-wine/ppa
- sudo add-apt-repository --yes ppa:arx/release
- sudo apt-get update -d
- sudo apt-get install -y -q innoextract wine python-software-properties
- wine --version
- innoextract --version
- "./scripts/innosetup/innoinstall.sh"
- sudo cp scripts/innosetup/iscc /usr/local/bin/iscc
- iscc /? 2> /dev/null | grep "Inno Setup Preprocessor"
# private keys for app
- if [ "${TRAVIS_SECURE_ENV_VARS}" != "false" ]; then openssl aes-256-cbc -K $encrypted_54b2df9dba46_key
  -iv $encrypted_54b2df9dba46_iv -in private.json.enc -out src/config/private.json
  -d; fi
# dropbox uploader key
- if [ "${TRAVIS_SECURE_ENV_VARS}" != "false" ]; then openssl aes-256-cbc -K $encrypted_8efd489acff0_key
  -iv $encrypted_8efd489acff0_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader
  -d; fi

# install git lfs
#- mkdir -p $HOME/bin
#- wget https://github.com/github/git-lfs/releases/download/v1.3.1/git-lfs-linux-amd64-1.3.1.tar.gz
#- tar xvfz git-lfs-linux-amd64-1.3.1.tar.gz
#- mv git-lfs-1.3.1/git-lfs $HOME/bin/git-lfs
#- export PATH=$PATH:$HOME/bin/
#- rm git-lfs-linux-amd64-1.3.1.tar.gz
before_script:
- git config --global url."https://".insteadOf git://
- npm ci
- npm i gulp -g
- npm i bower -g
#- npm install door43-client -g
script: npm test
after_success:
- test $TRAVIS_TEST_RESULT == 0 && $TRAVIS_PULL_REQUEST == "false"
- test -z $TRAVIS_TAG && ./scripts/bump.sh
#- door43-client index -i src/index/index.sqlite -f
- test -f src/index/index.sqlite
#- door43-client download -i src/index/index.sqlite -d src/index/resource_containers -f -c
- test -d src/index/resource_containers
- bower install
# ensure bower installed correctly
- test -d src/components
- gulp prince
# ensure prince was installed
- test -d src/prince
- gulp build --win
- gulp build --linux
- gulp build --osx
- gulp release
# upload to dropbox
- if [ -f ~/.dropbox_uploader ]; then
    echo 'uploading build to dropbox';
    ./dropbox_uploader.sh -q upload ./release/ travis-artifacts/$TRAVIS_JOB_NUMBER/;
  else
    echo 'missing ~/.dropbox_uploader. Skipping dropbox upload.';
  fi
#deploy:
## develop branch
#- provider: surge
#  project: "./release/"
#  domain: develop.ts-desktop.surge.sh
#  skip_cleanup: true
#  on:
#    branch: develop
#    condition: "-d ./release"
## catch-all
#- provider: surge
#  project: "./release/"
#  domain: sandbox.ts-desktop.surge.sh
#  skip_cleanup: true
#  on:
#    all_branches: true
#    tags: false
#    condition: "-d ./release && $TRAVIS_BRANCH != develop && ! ($TRAVIS_BRANCH =~ ^release-.*$) && $TRAVIS_BRANCH != master"
## release branch
#- provider: surge
#  project: "./release/"
#  domain: release.ts-desktop.surge.sh
#  skip_cleanup: true
#  on:
#    all_branches: true
#    tags: false
#    condition: "-d ./release && $TRAVIS_BRANCH =~ ^release-.*$"
# master branch
#- provider: releases
#  api_key:
#    secure: brjmL3cyCTr6swNCqka2fkc41j+PO2tqXZhE9QyNoDEXcxR1FOwPoPut/8h4N/pISfkf2FibtsWqThhW1Xz1pVNNMBlHRblJsSecfvXOtn7kneCsAV+QBngbPuA8OKzfhXTUeIQNlIpfG+rwlDg28wOthDI/7ADBOYgGQWeOd7o=
#  file:
#    - release/*.exe
#    - release/*.zip
#  file_glob: true
#  skip_cleanup: true
#  overwrite: true
#  on:
#    tags: true
#    repo: unfoldingWord-dev/ts-desktop
#    condition: "-d ./release"
